name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches:
      - main
      - fix-github-page
  workflow_dispatch:

concurrency:
  group: deploy-web
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install lightningcss native binary
        run: npm install lightningcss-linux-x64-gnu

      - name: Determine base paths
        id: base
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          if [ "$REPO_NAME" = "${GITHUB_REPOSITORY_OWNER}.github.io" ]; then
            BASE_PATH="/"
            BASE_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io"
          else
            BASE_PATH="/$REPO_NAME"
            BASE_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/$REPO_NAME"
          fi
          echo "base_path=$BASE_PATH" >> "$GITHUB_OUTPUT"
          echo "base_url=$BASE_URL" >> "$GITHUB_OUTPUT"

      - name: Build static web bundle
        env:
          EXPO_NO_DEBUG: "1"
          EXPO_USE_STATIC: "1"
          EXPO_NO_TELEMETRY: "1"
          EXPO_PUBLIC_BASE_URL: ${{ steps.base.outputs.base_url }}
          EXPO_PUBLIC_BASE_PATH: ${{ steps.base.outputs.base_path }}
        run: npx expo export --platform web --output-dir dist

      - name: Prepare Pages artifacts
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
